version: '3.8'

services:
  mongodb-local-data-api:
    build: .
    container_name: mongodb-local-data-api
    restart: always
    ports:
      - "${API_PORT}:${API_PORT}"
    environment:
      MONGO_USERNAME: "${MONGO_USERNAME}"
      MONGO_PASSWORD: "${MONGO_PASSWORD}"
      MONGO_PORT: "${MONGO_PORT}"
      MONGO_HOST: "${MONGO_HOST}"
      API_PORT: "${API_PORT}"
      API_KEY: "${API_KEY}"
    command: >
      mongodb-local-data-api
      --username=${MONGO_USERNAME}
      --password=${MONGO_PASSWORD}
      --mongodbHost=${MONGO_HOST}  # Use the external MongoDB host
      --mongodbPort=${MONGO_PORT}
      --apiPort=${API_PORT}
      --key=${API_KEY}
