version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "${MONGO_PORT}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_PASSWORD}"
    volumes:
      - mongodb_data:/data/db

  mongodb-local-data-api:
    build: .
    container_name: mongodb-local-data-api
    restart: always
    depends_on:
      - mongodb
    ports:
      - "${API_PORT}:${API_PORT}"
    environment:
      MONGO_USERNAME: "${MONGO_USERNAME}"
      MONGO_PASSWORD: "${MONGO_PASSWORD}"
      MONGO_PORT: "${MONGO_PORT}"
      API_PORT: "${API_PORT}"
      API_KEY: "${API_KEY}"
    command: >
      mongodb-local-data-api
      --username=${MONGO_USERNAME}
      --password=${MONGO_PASSWORD}
      --mongodbPort=${MONGO_PORT}
      --apiPort=${API_PORT}
      --key=${API_KEY}

volumes:
  mongodb_data:
